"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // 从 localStorage 读取保存的语言
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['zh', 'en', 'ms'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (mounted) {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key; // 如果找不到翻译，返回 key
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// 翻译字典
const translations: Record<Language, any> = {
  zh: {
    common: {
      home: '首页',
      services: '服务',
      lawyers: '律师',
      knowledge: '法律资讯',
      templates: '法律文档',
      about: '关于我们',
      contact: '联系我们',
      login: '登录',
      register: '注册',
      search: '搜索',
      viewAll: '查看全部',
      learnMore: '了解更多',
      getStarted: '立即开始',
      consultation: '在线咨询',
      submit: '提交',
      cancel: '取消',
      save: '保存',
      delete: '删除',
      edit: '编辑',
      back: '返回',
      next: '下一步',
      previous: '上一步',
      loading: '加载中...',
      noData: '暂无数据',
      error: '出错了',
      success: '成功',
      confirm: '确认',
      price: '价格',
      duration: '时长',
      cases: '案例',
      rating: '评分',
      reviews: '评价',
      hot: '热销',
      recommended: '推荐',
      new: '新',
    },
    header: {
      searchPlaceholder: '搜索律师、服务...',
      cart: '购物车',
      favorites: '收藏',
    },
    footer: {
      servicesTitle: '服务',
      lawyersTitle: '律师',
      aboutTitle: '关于',
      supportTitle: '支持',
      legalTitle: '法律',
      browseLawyers: '浏览律师',
      bookConsultation: '预约咨询',
      joinUs: '加入我们',
      aboutUs: '关于我们',
      legalNews: '法律资讯',
      contactUs: '联系我们',
      helpCenter: '帮助中心',
      faq: '常见问题',
      customerService: '联系客服',
      privacyPolicy: '隐私政策',
      termsOfService: '服务条款',
      copyright: '© 2026 LegalMY. All rights reserved.',
      location: '马来西亚 | Kuala Lumpur',
    },
    home: {
      heroTitle: '专业法律服务平台',
      heroSubtitle: '连接您与马来西亚最优秀的律师',
      heroDescription: '500+ 认证律师 | 2小时平均响应 | 4.9/5 客户评分',
      searchPlaceholder: '搜索法律服务或律师...',
      searchButton: '搜索',
      hotServicesTitle: '热门法律服务',
      hotServicesSubtitle: '选择您需要的法律服务类型',
      featuredLawyersTitle: '精选律师',
      featuredLawyersSubtitle: '经验丰富的专业律师为您服务',
      testimonialsTitle: '客户评价',
      testimonialsSubtitle: '看看其他客户怎么说',
      ctaTitle: '需要法律帮助？',
      ctaSubtitle: '立即咨询我们的专业律师团队',
      ctaButton: '在线咨询',
      ctaSecondary: '查看律师',
      hotSalesLawyers: '热销律师',
      recommendedForYou: '根据您的需求精准推荐',
      clientReviews: '客户评价',
      realExperience: '真实用户的咨询体验分享',
      basedOnReviews: '基于',
      reviewsCount: '条评价',
      verified: '已验证',
      helpful: '有用',
      reply: '回复',
      viewAllReviews: '查看全部评价',
      realClientReviews: '客户真实评价',
      trustedByClients: '超过 50,000 名客户选择信赖我们',
      averageRating: '平均评分',
      legalKnowledge: '法律知识库',
      legalKnowledgeDesc: '了解马来西亚法律知识，保护您的权益',
      readMore: '阅读更多',
      browseAllArticles: '浏览所有文章',
      faqTitle: '常见问题',
      faqSubtitle: '快速了解我们的服务',
      moreQuestions: '还有其他问题？',
      contactSupport: '联系客服',
      readyToSolve: '准备好解决您的',
      legalProblems: '法律问题了吗？',
      matchLawyer: '3 分钟内匹配专业律师，立即获得法律建议',
      freeConsultation: '限时优惠：首次咨询完全免费',
      startFreeConsultation: '开始免费咨询',
      emergencyHotline: '紧急热线',
      searchLawyers: '搜索律师...',
      filterBy: '筛选',
      sortBy: '排序',
      clearFilters: '清除筛选',
      priceRange: '价格范围',
      responseTime: '响应时间',
      location: '地区',
      specialty: '专业领域',
      all: '全部',
      hotSales: '热销',
      served: '已服务',
      people: '人',
      consult: '咨询',
      legalTemplates: '法律文书模板',
      professionalTemplates: '专业模板',
      freeDownload: '免费下载',
      browseTemplates: '浏览模板',
      onlineLawyerConsultation: '在线律师咨询',
      consultationFrom: '起咨询',
      replyWithin: '30分钟内回复',
      consultNow: '立即咨询',
      contractReview: '合同审核服务',
      reviewFrom: '起审核',
      professionalReview: '专业律师把关',
      submitReview: '提交审核',
      legalKnowledgeBase: '法律知识库',
      legalArticles: '法律文章',
      freeReading: '免费阅读',
      viewArticles: '查看文章',
      topLawyersRanking: '热销律师排行',
      weeklyUpdate: '本周更新',
      consultations: '次咨询',
      hotCategories: '热门服务分类',
      certifiedLawyers: '认证律师',
      avgResponse: '平均响应',
      clientRating: '客户评分',
      minutes: '分钟',
    },
    services: {
      title: '专业法律服务',
      subtitle: '涵盖7大法律领域，为您提供全方位的法律支持',
      debt: '债务纠纷',
      debtDesc: '债务追讨、破产申请、债务重组、债权人保护等债务法律事务',
      family: '家庭法',
      familyDesc: '离婚、监护权、财产分配、婚前协议等家庭法律事务',
      business: '商业法',
      businessDesc: '公司注册、合同审查、商业纠纷、知识产权保护',
      property: '房产法',
      propertyDesc: '房产买卖、租赁合同、产权纠纷、土地法律事务',
      criminal: '刑事法',
      criminalDesc: '刑事辩护、法律代理、保释申请、上诉服务',
      employment: '劳动法',
      employmentDesc: '劳动纠纷、不当解雇、工伤赔偿、劳动合同',
      ip: '知识产权',
      ipDesc: '专利申请、商标注册、版权保护、侵权诉讼',
      serviceContent: '服务内容：',
      priceRange: '价格范围：',
      estimatedTime: '预计时间：',
      consultNow: '立即咨询',
      serviceProcess: '服务流程',
      readyToStart: '准备开始了吗？',
      contactTeam: '联系我们的专业律师团队',
    },
    lawyers: {
      title: '专业律师',
      subtitle: '浏览我们的认证律师团队',
      searchPlaceholder: '搜索律师姓名或专业领域...',
      filterBySpecialty: '按专业筛选',
      allSpecialties: '所有专业',
      sortBy: '排序',
      sortByRating: '按评分',
      sortByPrice: '按价格',
      sortByExperience: '按经验',
      verified: '已认证',
      yearsExperience: '年经验',
      successRate: '成功率',
      consultationFee: '咨询费',
      viewProfile: '查看详情',
      bookConsultation: '预约咨询',
      addToFavorites: '添加收藏',
      addToCart: '加入购物车',
    },
    consultation: {
      title: '在线咨询',
      subtitle: '填写表单，我们会尽快与您联系',
      yourName: '您的姓名',
      yourEmail: '您的邮箱',
      yourPhone: '您的手机',
      selectService: '选择服务类型',
      selectLawyer: '选择律师（可选）',
      anyLawyer: '任意律师',
      consultationType: '咨询方式',
      online: '在线视频',
      phone: '电话咨询',
      inPerson: '线下面谈',
      preferredDate: '期望日期',
      preferredTime: '期望时间',
      caseDescription: '案件描述',
      caseDescriptionPlaceholder: '请详细描述您的法律问题...',
      submitConsultation: '提交咨询',
      successMessage: '咨询申请已提交！我们会在24小时内与您联系。',
    },
    auth: {
      loginTitle: '登录账户',
      loginSubtitle: '欢迎回来！请登录您的账户',
      registerTitle: '注册账户',
      registerSubtitle: '创建账户，开始使用我们的服务',
      email: '邮箱地址',
      password: '密码',
      confirmPassword: '确认密码',
      fullName: '全名',
      phone: '手机号码',
      rememberMe: '记住我',
      forgotPassword: '忘记密码？',
      loginButton: '登录',
      registerButton: '注册',
      noAccount: '还没有账户？',
      hasAccount: '已有账户？',
      signUp: '立即注册',
      signIn: '立即登录',
    },
    pages: {
      servicesTitle: '专业法律服务',
      servicesSubtitle: '涵盖7大法律领域，为您提供全方位的法律支持',
      serviceItems: '服务项目',
      serviceProcess: '服务流程',
      serviceContent: '服务内容',
      estimatedTime: '预计时间',
      readyToStart: '准备开始了吗？',
      contactTeam: '联系我们的专业律师团队',
      backToServices: '返回服务列表',
      lawyersTitle: '专业律师团队',
      lawyersSubtitle: '认证律师，为您提供专业法律服务',
      searchLawyerPlaceholder: '搜索律师姓名或专业领域...',
      filterConditions: '筛选条件',
      allFields: '全部领域',
      allLocations: '全部地区',
      allRatings: '全部评分',
      allStatus: '全部状态',
      online: '在线',
      offline: '离线',
      clearAllFilters: '清除所有筛选',
      found: '找到',
      lawyersCount: '位律师',
      loading: '加载中...',
      noLawyersFound: '未找到符合条件的律师',
      yearsExperience: '年经验',
      clientsServed: '位客户',
      responseTime: '响应时间',
      consultationTitle: '在线律师咨询',
      consultationSubtitle: '专业律师团队，30分钟内快速回复',
      consultationFrom: '起',
      minutesResponse: '分钟响应',
      professionalCertified: '专业认证',
      submitRequest: '提交咨询请求',
      yourName: '姓名',
      yourEmail: '电子邮箱',
      yourPhone: '电话号码',
      consultationCategory: '咨询类别',
      selectCategory: '请选择咨询类别',
      problemDescription: '问题描述',
      problemPlaceholder: '请详细描述您的法律问题...',
      submitting: '提交中...',
      submitConsultation: '提交咨询',
      consultationPrice: '咨询价格',
      perSession: '次',
      perMonth: '月',
      basicConsultation: '基础咨询服务',
      deepAnalysis: '深度法律分析',
      monthlyAdvisor: '包月法律顾问',
      serviceFeatures: '服务特点',
      quickResponse: '分钟内快速响应',
      professionalTeam: '专业认证律师团队',
      confidentialityAgreement: '保密协议保护',
      writtenOpinion: '书面法律意见',
      followUpService: '后续跟进服务',
      templatesTitle: '法律文书模板库',
      templatesSubtitle: '专业法律文书模板，符合马来西亚法律要求',
      searchTemplates: '搜索模板...',
      categoryFilter: '分类筛选',
      allTemplates: '全部',
      foundTemplates: '个模板',
      noTemplatesFound: '未找到相关模板',
      downloads: '下载',
      free: '免费',
      download: '下载',
      downloading: '下载中...',
      popularCategories: '热门分类',
      templates: '个模板',
      templateInfo: '模板信息',
      language: '语言',
      fileSize: '文件大小',
      format: '格式',
      lastUpdated: '最后更新',
      detailedDescription: '详细说明',
      templateFeatures: '模板特点',
      compliantWithLaw: '符合马来西亚法律要求',
      lawyerReviewed: '专业律师审核',
      editablePDF: '可编辑PDF格式',
      includesInstructions: '包含使用说明',
      downloadNow: '立即下载',
      knowledgeTitle: '法律知识库',
      knowledgeSubtitle: '法律文章，帮助您了解马来西亚法律知识',
      searchKnowledge: '搜索法律知识...',
      knowledgeCategories: '知识分类',
      allArticles: '全部文章',
      foundArticles: '篇文章',
      noArticlesFound: '未找到相关文章',
      minutesRead: '分钟阅读',
      views: '浏览',
      author: '作者',
      relatedLaws: '相关法律',
      readFullArticle: '阅读全文',
      popularCategoriesTitle: '热门分类',
      quickLinks: '快速链接',
      legalDocTemplates: '法律文书模板',
      consultLawyer: '咨询律师',
      onlineConsultation: '在线咨询',
    },
  },
  en: {
    common: {
      home: 'Home',
      services: 'Services',
      lawyers: 'Lawyers',
      knowledge: 'Legal Knowledge',
      templates: 'Legal Templates',
      about: 'About Us',
      contact: 'Contact',
      login: 'Login',
      register: 'Register',
      search: 'Search',
      viewAll: 'View All',
      learnMore: 'Learn More',
      getStarted: 'Get Started',
      consultation: 'Consultation',
      submit: 'Submit',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      loading: 'Loading...',
      noData: 'No Data',
      error: 'Error',
      success: 'Success',
      confirm: 'Confirm',
      price: 'Price',
      duration: 'Duration',
      cases: 'Cases',
      rating: 'Rating',
      reviews: 'Reviews',
      hot: 'Hot',
      recommended: 'Recommended',
      new: 'New',
    },
    header: {
      searchPlaceholder: 'Search lawyers, services...',
      cart: 'Cart',
      favorites: 'Favorites',
    },
    footer: {
      servicesTitle: 'Services',
      lawyersTitle: 'Lawyers',
      aboutTitle: 'About',
      supportTitle: 'Support',
      legalTitle: 'Legal',
      browseLawyers: 'Browse Lawyers',
      bookConsultation: 'Book Consultation',
      joinUs: 'Join Us',
      aboutUs: 'About Us',
      legalNews: 'Legal News',
      contactUs: 'Contact Us',
      helpCenter: 'Help Center',
      faq: 'FAQ',
      customerService: 'Customer Service',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      copyright: '© 2026 LegalMY. All rights reserved.',
      location: 'Malaysia | Kuala Lumpur',
    },
    home: {
      heroTitle: 'Professional Legal Services Platform',
      heroSubtitle: 'Connecting You with Malaysia\'s Best Lawyers',
      heroDescription: '500+ Certified Lawyers | 2h Average Response | 4.9/5 Client Rating',
      searchPlaceholder: 'Search legal services or lawyers...',
      searchButton: 'Search',
      hotServicesTitle: 'Popular Legal Services',
      hotServicesSubtitle: 'Choose the legal service you need',
      featuredLawyersTitle: 'Featured Lawyers',
      featuredLawyersSubtitle: 'Experienced professionals at your service',
      testimonialsTitle: 'Client Testimonials',
      testimonialsSubtitle: 'See what our clients say',
      ctaTitle: 'Need Legal Help?',
      ctaSubtitle: 'Consult with our professional legal team now',
      ctaButton: 'Online Consultation',
      ctaSecondary: 'View Lawyers',
      hotSalesLawyers: 'Top Lawyers',
      recommendedForYou: 'Recommended for your needs',
      clientReviews: 'Client Reviews',
      realExperience: 'Real user consultation experiences',
      basedOnReviews: 'Based on',
      reviewsCount: 'reviews',
      verified: 'Verified',
      helpful: 'Helpful',
      reply: 'Reply',
      viewAllReviews: 'View All Reviews',
      realClientReviews: 'Real Client Reviews',
      trustedByClients: 'Trusted by over 50,000 clients',
      averageRating: 'Average Rating',
      legalKnowledge: 'Legal Knowledge',
      legalKnowledgeDesc: 'Learn about Malaysian law and protect your rights',
      readMore: 'Read More',
      browseAllArticles: 'Browse All Articles',
      faqTitle: 'Frequently Asked Questions',
      faqSubtitle: 'Quick guide to our services',
      moreQuestions: 'Have more questions?',
      contactSupport: 'Contact Support',
      readyToSolve: 'Ready to solve your',
      legalProblems: 'legal problems?',
      matchLawyer: 'Match with a professional lawyer in 3 minutes',
      freeConsultation: 'Limited Offer: First consultation completely free',
      startFreeConsultation: 'Start Free Consultation',
      emergencyHotline: 'Emergency Hotline',
      searchLawyers: 'Search lawyers...',
      filterBy: 'Filter',
      sortBy: 'Sort By',
      clearFilters: 'Clear Filters',
      priceRange: 'Price Range',
      responseTime: 'Response Time',
      location: 'Location',
      specialty: 'Specialty',
      all: 'All',
      hotSales: 'Hot',
      served: 'Served',
      people: 'people',
      consult: 'Consult',
      legalTemplates: 'Legal Templates',
      professionalTemplates: 'Professional Templates',
      freeDownload: 'Free Download',
      browseTemplates: 'Browse Templates',
      onlineLawyerConsultation: 'Online Lawyer Consultation',
      consultationFrom: 'Consultation from',
      replyWithin: 'Reply within 30 minutes',
      consultNow: 'Consult Now',
      contractReview: 'Contract Review Service',
      reviewFrom: 'Review from',
      professionalReview: 'Professional lawyer review',
      submitReview: 'Submit Review',
      legalKnowledgeBase: 'Legal Knowledge Base',
      legalArticles: 'Legal Articles',
      freeReading: 'Free Reading',
      viewArticles: 'View Articles',
      topLawyersRanking: 'Top Lawyers Ranking',
      weeklyUpdate: 'Weekly Update',
      consultations: 'consultations',
      hotCategories: 'Popular Categories',
      certifiedLawyers: 'Certified Lawyers',
      avgResponse: 'Avg Response',
      clientRating: 'Client Rating',
      minutes: 'minutes',
    },
    services: {
      title: 'Professional Legal Services',
      subtitle: 'Covering 7 major legal areas to provide comprehensive support',
      debt: 'Debt Disputes',
      debtDesc: 'Debt collection, bankruptcy applications, debt restructuring, creditor protection',
      family: 'Family Law',
      familyDesc: 'Divorce, custody, property division, prenuptial agreements',
      business: 'Business Law',
      businessDesc: 'Company registration, contract review, business disputes, IP protection',
      property: 'Property Law',
      propertyDesc: 'Property transactions, lease agreements, title disputes, land matters',
      criminal: 'Criminal Law',
      criminalDesc: 'Criminal defense, legal representation, bail applications, appeals',
      employment: 'Employment Law',
      employmentDesc: 'Labor disputes, wrongful dismissal, work injury compensation, contracts',
      ip: 'Intellectual Property',
      ipDesc: 'Patent applications, trademark registration, copyright protection, infringement',
      serviceContent: 'Services:',
      priceRange: 'Price Range:',
      estimatedTime: 'Estimated Time:',
      consultNow: 'Consult Now',
      serviceProcess: 'Service Process',
      readyToStart: 'Ready to Start?',
      contactTeam: 'Contact our professional legal team',
    },
    lawyers: {
      title: 'Professional Lawyers',
      subtitle: 'Browse our certified legal team',
      searchPlaceholder: 'Search lawyer name or specialty...',
      filterBySpecialty: 'Filter by Specialty',
      allSpecialties: 'All Specialties',
      sortBy: 'Sort By',
      sortByRating: 'By Rating',
      sortByPrice: 'By Price',
      sortByExperience: 'By Experience',
      verified: 'Verified',
      yearsExperience: 'Years Experience',
      successRate: 'Success Rate',
      consultationFee: 'Consultation Fee',
      viewProfile: 'View Profile',
      bookConsultation: 'Book Consultation',
      addToFavorites: 'Add to Favorites',
      addToCart: 'Add to Cart',
    },
    consultation: {
      title: 'Online Consultation',
      subtitle: 'Fill out the form and we\'ll contact you soon',
      yourName: 'Your Name',
      yourEmail: 'Your Email',
      yourPhone: 'Your Phone',
      selectService: 'Select Service Type',
      selectLawyer: 'Select Lawyer (Optional)',
      anyLawyer: 'Any Lawyer',
      consultationType: 'Consultation Type',
      online: 'Online Video',
      phone: 'Phone Call',
      inPerson: 'In Person',
      preferredDate: 'Preferred Date',
      preferredTime: 'Preferred Time',
      caseDescription: 'Case Description',
      caseDescriptionPlaceholder: 'Please describe your legal issue in detail...',
      submitConsultation: 'Submit Consultation',
      successMessage: 'Consultation request submitted! We\'ll contact you within 24 hours.',
    },
    auth: {
      loginTitle: 'Login to Account',
      loginSubtitle: 'Welcome back! Please login to your account',
      registerTitle: 'Create Account',
      registerSubtitle: 'Create an account to start using our services',
      email: 'Email Address',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      fullName: 'Full Name',
      phone: 'Phone Number',
      rememberMe: 'Remember Me',
      forgotPassword: 'Forgot Password?',
      loginButton: 'Login',
      registerButton: 'Register',
      noAccount: 'Don\'t have an account?',
      hasAccount: 'Already have an account?',
      signUp: 'Sign Up',
      signIn: 'Sign In',
    },
    pages: {
      servicesTitle: 'Professional Legal Services',
      servicesSubtitle: 'Covering 7 major legal areas to provide comprehensive support',
      serviceItems: 'Service Items',
      serviceProcess: 'Service Process',
      serviceContent: 'Services',
      estimatedTime: 'Estimated Time',
      readyToStart: 'Ready to Start?',
      contactTeam: 'Contact our professional legal team',
      backToServices: 'Back to Services',
      lawyersTitle: 'Professional Legal Team',
      lawyersSubtitle: 'Certified lawyers providing professional legal services',
      searchLawyerPlaceholder: 'Search lawyer name or specialty...',
      filterConditions: 'Filter Conditions',
      allFields: 'All Fields',
      allLocations: 'All Locations',
      allRatings: 'All Ratings',
      allStatus: 'All Status',
      online: 'Online',
      offline: 'Offline',
      clearAllFilters: 'Clear All Filters',
      found: 'Found',
      lawyersCount: 'lawyers',
      loading: 'Loading...',
      noLawyersFound: 'No lawyers found matching criteria',
      yearsExperience: 'years experience',
      clientsServed: 'clients',
      responseTime: 'Response time',
      consultationTitle: 'Online Lawyer Consultation',
      consultationSubtitle: 'Professional legal team, quick response within 30 minutes',
      consultationFrom: 'from',
      minutesResponse: 'minutes response',
      professionalCertified: 'Professional Certified',
      submitRequest: 'Submit Consultation Request',
      yourName: 'Name',
      yourEmail: 'Email',
      yourPhone: 'Phone',
      consultationCategory: 'Consultation Category',
      selectCategory: 'Please select category',
      problemDescription: 'Problem Description',
      problemPlaceholder: 'Please describe your legal issue in detail...',
      submitting: 'Submitting...',
      submitConsultation: 'Submit Consultation',
      consultationPrice: 'Consultation Price',
      perSession: 'session',
      perMonth: 'month',
      basicConsultation: 'Basic Consultation Service',
      deepAnalysis: 'Deep Legal Analysis',
      monthlyAdvisor: 'Monthly Legal Advisor',
      serviceFeatures: 'Service Features',
      quickResponse: 'minutes quick response',
      professionalTeam: 'Professional certified legal team',
      confidentialityAgreement: 'Confidentiality agreement protection',
      writtenOpinion: 'Written legal opinion',
      followUpService: 'Follow-up service',
      templatesTitle: 'Legal Document Templates Library',
      templatesSubtitle: 'Professional legal document templates compliant with Malaysian law',
      searchTemplates: 'Search templates...',
      categoryFilter: 'Category Filter',
      allTemplates: 'All',
      foundTemplates: 'templates',
      noTemplatesFound: 'No templates found',
      downloads: 'downloads',
      free: 'Free',
      download: 'Download',
      downloading: 'Downloading...',
      popularCategories: 'Popular Categories',
      templates: 'templates',
      templateInfo: 'Template Information',
      language: 'Language',
      fileSize: 'File Size',
      format: 'Format',
      lastUpdated: 'Last Updated',
      detailedDescription: 'Detailed Description',
      templateFeatures: 'Template Features',
      compliantWithLaw: 'Compliant with Malaysian law',
      lawyerReviewed: 'Lawyer reviewed',
      editablePDF: 'Editable PDF format',
      includesInstructions: 'Includes instructions',
      downloadNow: 'Download Now',
      knowledgeTitle: 'Legal Knowledge Base',
      knowledgeSubtitle: 'legal articles to help you understand Malaysian law',
      searchKnowledge: 'Search legal knowledge...',
      knowledgeCategories: 'Knowledge Categories',
      allArticles: 'All Articles',
      foundArticles: 'articles',
      noArticlesFound: 'No articles found',
      minutesRead: 'minutes read',
      views: 'views',
      author: 'Author',
      relatedLaws: 'Related Laws',
      readFullArticle: 'Read Full Article',
      popularCategoriesTitle: 'Popular Categories',
      quickLinks: 'Quick Links',
      legalDocTemplates: 'Legal Document Templates',
      consultLawyer: 'Consult Lawyer',
      onlineConsultation: 'Online Consultation',
    },
  },
  ms: {
    common: {
      home: 'Laman Utama',
      services: 'Perkhidmatan',
      lawyers: 'Peguam',
      knowledge: 'Pengetahuan Undang-undang',
      templates: 'Templat Undang-undang',
      about: 'Tentang Kami',
      contact: 'Hubungi',
      login: 'Log Masuk',
      register: 'Daftar',
      search: 'Cari',
      viewAll: 'Lihat Semua',
      learnMore: 'Ketahui Lebih Lanjut',
      getStarted: 'Mulakan',
      consultation: 'Perundingan',
      submit: 'Hantar',
      cancel: 'Batal',
      save: 'Simpan',
      delete: 'Padam',
      edit: 'Edit',
      back: 'Kembali',
      next: 'Seterusnya',
      previous: 'Sebelumnya',
      loading: 'Memuatkan...',
      noData: 'Tiada Data',
      error: 'Ralat',
      success: 'Berjaya',
      confirm: 'Sahkan',
      price: 'Harga',
      duration: 'Tempoh',
      cases: 'Kes',
      rating: 'Penilaian',
      reviews: 'Ulasan',
      hot: 'Popular',
      recommended: 'Disyorkan',
      new: 'Baru',
    },
    header: {
      searchPlaceholder: 'Cari peguam, perkhidmatan...',
      cart: 'Troli',
      favorites: 'Kegemaran',
    },
    footer: {
      servicesTitle: 'Perkhidmatan',
      lawyersTitle: 'Peguam',
      aboutTitle: 'Tentang',
      supportTitle: 'Sokongan',
      legalTitle: 'Undang-undang',
      browseLawyers: 'Layari Peguam',
      bookConsultation: 'Tempah Perundingan',
      joinUs: 'Sertai Kami',
      aboutUs: 'Tentang Kami',
      legalNews: 'Berita Undang-undang',
      contactUs: 'Hubungi Kami',
      helpCenter: 'Pusat Bantuan',
      faq: 'Soalan Lazim',
      customerService: 'Khidmat Pelanggan',
      privacyPolicy: 'Dasar Privasi',
      termsOfService: 'Terma Perkhidmatan',
      copyright: '© 2026 LegalMY. Hak cipta terpelihara.',
      location: 'Malaysia | Kuala Lumpur',
    },
    home: {
      heroTitle: 'Platform Perkhidmatan Undang-undang Profesional',
      heroSubtitle: 'Menghubungkan Anda dengan Peguam Terbaik Malaysia',
      heroDescription: '500+ Peguam Bertauliah | 2j Respons Purata | 4.9/5 Penilaian Klien',
      searchPlaceholder: 'Cari perkhidmatan undang-undang atau peguam...',
      searchButton: 'Cari',
      hotServicesTitle: 'Perkhidmatan Undang-undang Popular',
      hotServicesSubtitle: 'Pilih jenis perkhidmatan undang-undang yang anda perlukan',
      featuredLawyersTitle: 'Peguam Pilihan',
      featuredLawyersSubtitle: 'Profesional berpengalaman untuk perkhidmatan anda',
      testimonialsTitle: 'Testimoni Klien',
      testimonialsSubtitle: 'Lihat apa yang klien kami katakan',
      ctaTitle: 'Perlukan Bantuan Undang-undang?',
      ctaSubtitle: 'Berunding dengan pasukan undang-undang profesional kami sekarang',
      ctaButton: 'Perundingan Dalam Talian',
      ctaSecondary: 'Lihat Peguam',
      hotSalesLawyers: 'Peguam Teratas',
      recommendedForYou: 'Disyorkan untuk keperluan anda',
      clientReviews: 'Ulasan Klien',
      realExperience: 'Pengalaman perundingan pengguna sebenar',
      basedOnReviews: 'Berdasarkan',
      reviewsCount: 'ulasan',
      verified: 'Disahkan',
      helpful: 'Berguna',
      reply: 'Balas',
      viewAllReviews: 'Lihat Semua Ulasan',
      realClientReviews: 'Ulasan Klien Sebenar',
      trustedByClients: 'Dipercayai oleh lebih 50,000 klien',
      averageRating: 'Penilaian Purata',
      legalKnowledge: 'Pengetahuan Undang-undang',
      legalKnowledgeDesc: 'Ketahui undang-undang Malaysia dan lindungi hak anda',
      readMore: 'Baca Lagi',
      browseAllArticles: 'Layari Semua Artikel',
      faqTitle: 'Soalan Lazim',
      faqSubtitle: 'Panduan pantas untuk perkhidmatan kami',
      moreQuestions: 'Ada soalan lagi?',
      contactSupport: 'Hubungi Sokongan',
      readyToSolve: 'Bersedia untuk menyelesaikan',
      legalProblems: 'masalah undang-undang anda?',
      matchLawyer: 'Padankan dengan peguam profesional dalam 3 minit',
      freeConsultation: 'Tawaran Terhad: Perundingan pertama percuma sepenuhnya',
      startFreeConsultation: 'Mulakan Perundingan Percuma',
      emergencyHotline: 'Talian Kecemasan',
      searchLawyers: 'Cari peguam...',
      filterBy: 'Tapis',
      sortBy: 'Isih Mengikut',
      clearFilters: 'Kosongkan Penapis',
      priceRange: 'Julat Harga',
      responseTime: 'Masa Respons',
      location: 'Lokasi',
      specialty: 'Kepakaran',
      all: 'Semua',
      hotSales: 'Popular',
      served: 'Berkhidmat',
      people: 'orang',
      consult: 'Berunding',
      legalTemplates: 'Templat Undang-undang',
      professionalTemplates: 'Templat Profesional',
      freeDownload: 'Muat Turun Percuma',
      browseTemplates: 'Layari Templat',
      onlineLawyerConsultation: 'Perundingan Peguam Dalam Talian',
      consultationFrom: 'Perundingan dari',
      replyWithin: 'Balas dalam masa 30 minit',
      consultNow: 'Berunding Sekarang',
      contractReview: 'Perkhidmatan Semakan Kontrak',
      reviewFrom: 'Semakan dari',
      professionalReview: 'Semakan peguam profesional',
      submitReview: 'Hantar Semakan',
      legalKnowledgeBase: 'Pangkalan Pengetahuan Undang-undang',
      legalArticles: 'Artikel Undang-undang',
      freeReading: 'Bacaan Percuma',
      viewArticles: 'Lihat Artikel',
      topLawyersRanking: 'Kedudukan Peguam Teratas',
      weeklyUpdate: 'Kemas Kini Mingguan',
      consultations: 'perundingan',
      hotCategories: 'Kategori Popular',
      certifiedLawyers: 'Peguam Bertauliah',
      avgResponse: 'Respons Purata',
      clientRating: 'Penilaian Klien',
      minutes: 'minit',
    },
    services: {
      title: 'Perkhidmatan Undang-undang Profesional',
      subtitle: 'Meliputi 7 bidang undang-undang utama untuk sokongan menyeluruh',
      debt: 'Pertikaian Hutang',
      debtDesc: 'Kutipan hutang, permohonan kebankrapan, penstrukturan semula hutang, perlindungan pemiutang',
      family: 'Undang-undang Keluarga',
      familyDesc: 'Perceraian, hak penjagaan, pembahagian harta, perjanjian pranikah',
      business: 'Undang-undang Perniagaan',
      businessDesc: 'Pendaftaran syarikat, semakan kontrak, pertikaian perniagaan, perlindungan IP',
      property: 'Undang-undang Harta',
      propertyDesc: 'Transaksi hartanah, perjanjian sewa, pertikaian hak milik, hal tanah',
      criminal: 'Undang-undang Jenayah',
      criminalDesc: 'Pembelaan jenayah, perwakilan undang-undang, permohonan jaminan, rayuan',
      employment: 'Undang-undang Pekerjaan',
      employmentDesc: 'Pertikaian buruh, pemecatan salah, pampasan kecederaan kerja, kontrak',
      ip: 'Harta Intelek',
      ipDesc: 'Permohonan paten, pendaftaran cap dagangan, perlindungan hak cipta, pelanggaran',
      serviceContent: 'Perkhidmatan:',
      priceRange: 'Julat Harga:',
      estimatedTime: 'Anggaran Masa:',
      consultNow: 'Berunding Sekarang',
      serviceProcess: 'Proses Perkhidmatan',
      readyToStart: 'Bersedia untuk Bermula?',
      contactTeam: 'Hubungi pasukan undang-undang profesional kami',
    },
    lawyers: {
      title: 'Peguam Profesional',
      subtitle: 'Layari pasukan undang-undang bertauliah kami',
      searchPlaceholder: 'Cari nama peguam atau kepakaran...',
      filterBySpecialty: 'Tapis mengikut Kepakaran',
      allSpecialties: 'Semua Kepakaran',
      sortBy: 'Isih Mengikut',
      sortByRating: 'Mengikut Penilaian',
      sortByPrice: 'Mengikut Harga',
      sortByExperience: 'Mengikut Pengalaman',
      verified: 'Disahkan',
      yearsExperience: 'Tahun Pengalaman',
      successRate: 'Kadar Kejayaan',
      consultationFee: 'Yuran Perundingan',
      viewProfile: 'Lihat Profil',
      bookConsultation: 'Tempah Perundingan',
      addToFavorites: 'Tambah ke Kegemaran',
      addToCart: 'Tambah ke Troli',
    },
    consultation: {
      title: 'Perundingan Dalam Talian',
      subtitle: 'Isi borang dan kami akan menghubungi anda tidak lama lagi',
      yourName: 'Nama Anda',
      yourEmail: 'Emel Anda',
      yourPhone: 'Telefon Anda',
      selectService: 'Pilih Jenis Perkhidmatan',
      selectLawyer: 'Pilih Peguam (Pilihan)',
      anyLawyer: 'Mana-mana Peguam',
      consultationType: 'Jenis Perundingan',
      online: 'Video Dalam Talian',
      phone: 'Panggilan Telefon',
      inPerson: 'Secara Peribadi',
      preferredDate: 'Tarikh Pilihan',
      preferredTime: 'Masa Pilihan',
      caseDescription: 'Penerangan Kes',
      caseDescriptionPlaceholder: 'Sila huraikan isu undang-undang anda dengan terperinci...',
      submitConsultation: 'Hantar Perundingan',
      successMessage: 'Permintaan perundingan dihantar! Kami akan menghubungi anda dalam masa 24 jam.',
    },
    auth: {
      loginTitle: 'Log Masuk ke Akaun',
      loginSubtitle: 'Selamat kembali! Sila log masuk ke akaun anda',
      registerTitle: 'Cipta Akaun',
      registerSubtitle: 'Cipta akaun untuk mula menggunakan perkhidmatan kami',
      email: 'Alamat Emel',
      password: 'Kata Laluan',
      confirmPassword: 'Sahkan Kata Laluan',
      fullName: 'Nama Penuh',
      phone: 'Nombor Telefon',
      rememberMe: 'Ingat Saya',
      forgotPassword: 'Lupa Kata Laluan?',
      loginButton: 'Log Masuk',
      registerButton: 'Daftar',
      noAccount: 'Tidak mempunyai akaun?',
      hasAccount: 'Sudah mempunyai akaun?',
      signUp: 'Daftar',
      signIn: 'Log Masuk',
    },
    pages: {
      servicesTitle: 'Perkhidmatan Undang-undang Profesional',
      servicesSubtitle: 'Meliputi 7 bidang undang-undang utama untuk sokongan menyeluruh',
      serviceItems: 'Item Perkhidmatan',
      serviceProcess: 'Proses Perkhidmatan',
      serviceContent: 'Perkhidmatan',
      estimatedTime: 'Anggaran Masa',
      readyToStart: 'Bersedia untuk Bermula?',
      contactTeam: 'Hubungi pasukan undang-undang profesional kami',
      backToServices: 'Kembali ke Perkhidmatan',
      lawyersTitle: 'Pasukan Undang-undang Profesional',
      lawyersSubtitle: 'Peguam bertauliah menyediakan perkhidmatan undang-undang profesional',
      searchLawyerPlaceholder: 'Cari nama peguam atau kepakaran...',
      filterConditions: 'Syarat Penapis',
      allFields: 'Semua Bidang',
      allLocations: 'Semua Lokasi',
      allRatings: 'Semua Penilaian',
      allStatus: 'Semua Status',
      online: 'Dalam Talian',
      offline: 'Luar Talian',
      clearAllFilters: 'Kosongkan Semua Penapis',
      found: 'Dijumpai',
      lawyersCount: 'peguam',
      loading: 'Memuatkan...',
      noLawyersFound: 'Tiada peguam dijumpai yang memenuhi kriteria',
      yearsExperience: 'tahun pengalaman',
      clientsServed: 'klien',
      responseTime: 'Masa respons',
      consultationTitle: 'Perundingan Peguam Dalam Talian',
      consultationSubtitle: 'Pasukan undang-undang profesional, respons pantas dalam masa 30 minit',
      consultationFrom: 'dari',
      minutesResponse: 'minit respons',
      professionalCertified: 'Bertauliah Profesional',
      submitRequest: 'Hantar Permintaan Perundingan',
      yourName: 'Nama',
      yourEmail: 'Emel',
      yourPhone: 'Telefon',
      consultationCategory: 'Kategori Perundingan',
      selectCategory: 'Sila pilih kategori',
      problemDescription: 'Penerangan Masalah',
      problemPlaceholder: 'Sila huraikan isu undang-undang anda dengan terperinci...',
      submitting: 'Menghantar...',
      submitConsultation: 'Hantar Perundingan',
      consultationPrice: 'Harga Perundingan',
      perSession: 'sesi',
      perMonth: 'bulan',
      basicConsultation: 'Perkhidmatan Perundingan Asas',
      deepAnalysis: 'Analisis Undang-undang Mendalam',
      monthlyAdvisor: 'Penasihat Undang-undang Bulanan',
      serviceFeatures: 'Ciri Perkhidmatan',
      quickResponse: 'minit respons pantas',
      professionalTeam: 'Pasukan undang-undang bertauliah profesional',
      confidentialityAgreement: 'Perlindungan perjanjian kerahsiaan',
      writtenOpinion: 'Pendapat undang-undang bertulis',
      followUpService: 'Perkhidmatan susulan',
      templatesTitle: 'Perpustakaan Templat Dokumen Undang-undang',
      templatesSubtitle: 'Templat dokumen undang-undang profesional mematuhi undang-undang Malaysia',
      searchTemplates: 'Cari templat...',
      categoryFilter: 'Penapis Kategori',
      allTemplates: 'Semua',
      foundTemplates: 'templat',
      noTemplatesFound: 'Tiada templat dijumpai',
      downloads: 'muat turun',
      free: 'Percuma',
      download: 'Muat Turun',
      downloading: 'Memuat turun...',
      popularCategories: 'Kategori Popular',
      templates: 'templat',
      templateInfo: 'Maklumat Templat',
      language: 'Bahasa',
      fileSize: 'Saiz Fail',
      format: 'Format',
      lastUpdated: 'Kemas Kini Terakhir',
      detailedDescription: 'Penerangan Terperinci',
      templateFeatures: 'Ciri Templat',
      compliantWithLaw: 'Mematuhi undang-undang Malaysia',
      lawyerReviewed: 'Disemak oleh peguam',
      editablePDF: 'Format PDF boleh edit',
      includesInstructions: 'Termasuk arahan',
      downloadNow: 'Muat Turun Sekarang',
      knowledgeTitle: 'Pangkalan Pengetahuan Undang-undang',
      knowledgeSubtitle: 'artikel undang-undang untuk membantu anda memahami undang-undang Malaysia',
      searchKnowledge: 'Cari pengetahuan undang-undang...',
      knowledgeCategories: 'Kategori Pengetahuan',
      allArticles: 'Semua Artikel',
      foundArticles: 'artikel',
      noArticlesFound: 'Tiada artikel dijumpai',
      minutesRead: 'minit bacaan',
      views: 'tontonan',
      author: 'Pengarang',
      relatedLaws: 'Undang-undang Berkaitan',
      readFullArticle: 'Baca Artikel Penuh',
      popularCategoriesTitle: 'Kategori Popular',
      quickLinks: 'Pautan Pantas',
      legalDocTemplates: 'Templat Dokumen Undang-undang',
      consultLawyer: 'Berunding dengan Peguam',
      onlineConsultation: 'Perundingan Dalam Talian',
    },
  },
};
